//FABIAN MAURICIO CONDORENA LAZARTE;
#include <iostream>
using namespace std;
int main ()
{
    system("cls");
    int numero1 = 0;
    int numero2 = 0;
    int suma =0;
    int i;
    cout << "ingrese el numero 1"; 
    cin >> numero1;
    for (i =1; i >numero1;i++ )
        {
            if (numero1%i==0)
            {  
                suma+=numero1%i;
            }     
            else 
            {   

            }

     if (suma==numero1==true)
     { 
        cout << " el numero ingresado es amigo";

     }          

 
            





        







    return 0;
}


